# Generated by Django 4.1.4 on 2023-01-20 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_rename_image_article_image_url_article_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
