# Generated by Django 4.1.4 on 2023-04-18 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0007_article_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_posted',
            field=models.BooleanField(default=True),
        ),
    ]
