# Generated by Django 4.1.4 on 2023-04-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0008_alter_article_is_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('FE', 'Front-end'), ('BE', 'Back-end'), ('FS', 'Full-Stack'), ('PY', 'Python'), ('DJ', 'Django'), ('JS', 'JavaScript'), ('RJ', 'ReactJs'), ('RN', 'React Native'), ('ND', 'NodeJS')], default='', max_length=255),
        ),
    ]
