# Generated by Django 4.1.4 on 2023-01-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
    ]
