# Generated by Django 4.1.4 on 2023-01-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_alter_article_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image',
            new_name='image_url',
        ),
        migrations.AddField(
            model_name='article',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
